//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*! \file Settings.Designer.cs
\brief Plik Settings.Designer.cs zawiera klasę Password_Manager.Properties z ustawieniami aplikacji.

Plik Settings.Designer.cs zawiera klasę Password_Manager.Properties z ustawieniami aplikacji.
Plik ten jest generowany automatycznie przez Visual Studio i nie powinnien być modyfikowany ręcznie.
*/

//! Przestrzeń nazw Password_Manager.Properties zawiera ustawienia aplikacji.
/*! Password_Manager.Properties jest generowana automatycznie przez Visual Studio i nie powinna być zmieniania ręcznie. 
 * Definiuje ona ustawienia aplikacji oraz wykorzystywane przez nią zasoby.
 */
namespace Password_Manager.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
